owner: cravemob
repo: mog-status
user-agent: mog-status
sites:
  - name: Mog (dev)
    url: http://ec2-13-125-98-107.ap-northeast-2.compute.amazonaws.com:30000
notifications:
  - type: slack
    channel: G017XTR46Q5
assignees:
  - CravemobRogerYoo
status-website:
  cname: mog-status.elchronicle.io
  logoUrl: http://mog-status.elchronicle.io/icon51.svg
  name: mog-status
  introTitle: 
  introMessage: 
