owner: cravemob
repo: mog-status
user-agent: mog-status
sites:
  - name: Epic Fantasy 1
    url: http://3.34.157.104:20000/ping
  - name: Epic Fantasy 2
    url: http://3.35.94.253:20000/ping
 - name: Mog (release)
    url: http://15.164.136.6:30000    
notifications:
  - type: slack
    channel: G017XTR46Q5
assignees:
  - CravemobRogerYoo
status-website:
  cname: mog-status.elchronicle.io
  logoUrl: https://raw.githubusercontent.com/koj-co/upptime/79d9d1c22ecf706acc51f17798d7c7dbc710ab40/assets/icon.svg	
  name: mog-status
  introTitle: 
  introMessage: 
