owner: cravemob
repo: mog-status
user-agent: mog-status
sites:
  - name: Google
    url: https://www.google.com
notifications:
  - type: slack
    channel: 323
assignees:
  - CravemobRogerYoo
status-website:
  cname: mog-status.elchronicle.io
  logoUrl: https://raw.githubusercontent.com/koj-co/upptime/79d9d1c22ecf706acc51f17798d7c7dbc710ab40/assets/icon.svg
  name: mog-status
  introTitle: 
  introMessage: 
